version: "3.8"
services:
  app:
    image: metavinayak/matrix
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    ports:
      - "8000-8002:3000"
    networks:
      - my-network
networks:
  my-network:
